#server:
#  port: 9001
#  servlet:
#    encoding:
#      force: true
#      charset: UTF-8
#
#spring:
#  application:
#    name: user-service
#  cloud:
#    #注册中⼼地址
#    nacos:
#      discovery:
#        server-addr: 140.143.141.194:8848
#  #消息队列
#  rabbitmq:
#    host: 140.143.141.194
#    port: 5672
#    virtual-host: /dev
#    password: password
#    username: admin
#    #开启手动确认消息
#    listener:
#      simple:
#        acknowledge-mode: manual
#  #数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#  redis:
#    host: 140.143.141.194
#    port: 6379
#    password: redispsw
#  #邮箱服务配置
#  mail:
#    host: smtp.163.com #发送邮件服务器
#    username: xxxx #发送邮件的邮箱地址
#    password: xxx #客户端授权码，不是邮箱密码,网易的是自己设置的
#    from: xxx # 发送邮件的地址，和上面username一致
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
##配置plus打印sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#
##设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
#logging:
#  level:
#    root: INFO
#
#oss:
#  secretId: xxxFF
#  secretKey: xxx
#  region: ap-beijing
#
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#
##seata:
##  tx-service-group: ${spring.application.name}-group
##  service:
##    grouplist:
##      shop: 127.0.0.1:8091
##    vgroup-mapping:
##      user-service-group: shop
